# -*- mode: ruby -*-
# vi: set ft=ruby :

PUBLIC_IP = ENV['ANSIBLE_VAGRANT_PUBLIC_IP'] || '10.1.1.44'

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network", ip: PUBLIC_IP, bridge: 'en0: Wi-Fi (AirPort)'

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = 'vvvv'
    ansible.sudo = true
    ansible.tags = 'users'
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2000"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

end