FROM forthepet

ENV DEBIAN_FRONTEND=noninteractive
ENV PHANTOMJS phantomjs-2.1.1-linux-x86_64

RUN apt-get update && apt-get install -yq wget
RUN mkdir /downloads && \
    wget -qN https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOMJS.tar.bz2 -P /downloads && \
    tar xjf /downloads/$PHANTOMJS.tar.bz2 -C /downloads && \
    cp /downloads/$PHANTOMJS/bin/phantomjs /usr/bin/phantomjs && \
    echo "unsafe-perm = true" > /root/.npmrc

CMD passenger start
