version: '2'
services:
  pg_data:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
      - ./backups/:/backups

  bundle:
    image: busybox
    volumes:
      - /bundle

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
    volumes_from:
    - pg_data

  # maildev:
  #   image: djfarrelly/maildev:0.13.3
  #   ports:
  #     - "1080:80"
  #     - "1025:25"

  mailcatcher:
    image: tophfr/mailcatcher:latest
    # image: schickling/mailcatcher
    ports:
      - "1080:80"
      - "1025:25"

  worker:
    extends:
      file: common.yml
      service: common_web
    command: bundle exec rake jobs:work
    volumes_from:
      - bundle
    links:
      - db
      - mailcatcher

  web:
    extends:
      file: common.yml
      service: common_web
    command: passenger start
    volumes_from:
      - bundle
    ports:
      - "3000:3000"
    links:
      - db
      - mailcatcher
