source 'https://rubygems.org'

gem 'rails', '4.2.5'

group :assets do
  gem 'sass-rails', '~> 5.0.3'
  gem 'uglifier', '~> 3.0.0'
end

group :development do
  gem 'pry-rails'
  gem 'better_errors', '~> 2.1.1'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'quiet_assets', '~> 1.1.0'
  gem 'guard-rspec', '~> 4.5.0'
  gem 'spring'
  gem 'rubocop', require: false
  gem 'rack-mini-profiler'
  gem 'bullet'
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rbenv'
  gem 'capistrano-rails'
  gem 'capistrano-nc'
  gem 'capistrano3-delayed-job', '~> 1.0'
  gem 'capistrano-passenger', '= 0.0.1'
  gem "capistrano-scm-gitcopy"
end

group :test do
  gem 'capybara'
  gem 'faker'
  gem 'shoulda-matchers'
  gem 'simplecov', :require => false
  gem 'database_cleaner'
end

group :development, :test do
  gem 'foreman', require: false
  gem 'rspec-rails'
  gem 'rspec-collection_matchers'
  gem 'spring-commands-rspec'
  gem 'factory_girl_rails'
end

# admin specific gems
gem 'tinymce-rails', '~> 4.1.6'
gem 'ransack', '~> 1.6.6'
gem 'aasm', '~> 4.1.1'
gem 'cancancan', '~> 1.10.1'
gem 'kaminari', '~> 0.16.3'

# other gems
gem 'exception_handler', '~> 0.3.45'
gem 'autoprefixer-rails', '~> 5.1.11'
gem 'bootstrap-sass', '~> 3.3.4.1'
gem 'momentjs-rails', '~> 2.8.1'
gem 'bootstrap3-datetimepicker-rails', '~> 4.7.14'
gem 'roadie-rails', '~> 1.0.6'
gem 'metamagic', '~> 3.1.7'
gem 'delayed_job_active_record', '~> 4.0.3'
gem 'zeroclipboard-rails', '~> 0.1.0'
gem 'roboto', '~> 0.2.0'
gem 'jquery-cookie-rails', '~> 1.3.1.1'
gem 'acts_as_list', '~> 0.7.2'

gem 'pg', '~> 0.18.4'
gem 'jquery-rails', '~> 4.0.3'
gem 'jquery-ui-rails', '~> 5.0.5'
gem 'devise', '~> 3.4.1'
gem 'carrierwave', '~> 0.10.0'
gem 'cloudinary', '~> 1.1.6'
gem 'mandrill-api', '~> 1.0.53'
gem 'wicked', '~> 1.1.1'
gem 'simple_form', git: 'https://github.com/plataformatec/simple_form.git'
gem 'crummy', '~> 1.8.0'
gem 'friendly_id', '~> 5.1.0'
gem 'slim-rails', git: 'https://github.com/slim-template/slim-rails.git'
gem 'newrelic_rpm', '~> 3.12.0.288'
gem 'braintree', '~> 2.47.0'
gem 'draper', '~> 2.1.0'
gem 'font-awesome-rails', '~> 4.3.0.0'
gem 'seed_dumper', '~> 0.1.3'
gem 'gibbon', '~> 1.1.5'
gem 'daemons', '~> 1.2.2'
gem 'rollbar', '~> 2.11.1'
gem 'skylight', '~> 0.6.0'
gem 'reform', '~> 1.2.6'
gem 'daemon_controller', '~> 1.2.0'
