source 'https://rubygems.org'

gem 'rails', '4.2.7.1'

group :assets do
  gem 'sass-rails'
  gem 'uglifier'
  gem 'coffee-script', '~> 2.4.1'
end

group :development do
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'quiet_assets', '~> 1.1.0'
  gem 'guard-rspec', '~> 4.5.0'
  gem 'spring'
  gem 'rubocop', require: false
  gem 'rack-mini-profiler'
  gem 'bullet'
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rbenv'
  gem 'capistrano-rails'
  gem 'capistrano-nc'
  gem 'capistrano3-delayed-job', '~> 1.0'
  gem 'capistrano-passenger', '= 0.0.1'
  gem "capistrano-scm-gitcopy"
end

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'faker'
  gem 'shoulda-matchers'
  gem 'simplecov', :require => false
  gem 'database_cleaner'
end

group :development, :test do
  gem 'foreman', require: false
  gem 'rspec-rails'
  gem 'rspec-collection_matchers'
  gem 'spring-commands-rspec'
  gem 'factory_girl_rails'
end

# admin specific gems
gem 'tinymce-rails', '~> 4.1.6'
gem 'ransack', '~> 1.6.6'
gem 'aasm', '~> 4.10.1'
gem 'cancancan', '~> 1.14.0'
gem 'kaminari', '~> 0.17.0'

# other gems
gem 'exception_handler', '~> 0.3.45'
gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'momentjs-rails', '~> 2.8.1'
gem 'roadie-rails', '~> 1.0.6'
gem 'metamagic', '~> 3.1.7'
gem 'delayed_job_active_record'
gem 'zeroclipboard-rails'
gem 'roboto', '~> 0.2.0'
gem 'jquery-cookie-rails', '~> 1.3.1.1'
gem 'acts_as_list', '~> 0.7.4'

gem 'pg', '~> 0.18.4'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'devise', '~> 3.5.10'
gem 'carrierwave', '~> 0.11.2'
gem 'cloudinary'
gem 'wicked'
gem 'simple_form', '~> 3.1.0'
gem 'crummy', '~> 1.8.0'
gem 'friendly_id', '~> 5.1.0'
gem 'slim-rails'
gem 'newrelic_rpm'
gem 'braintree', '~> 2.65.0'
gem 'draper', '~> 2.1.0'
gem 'font-awesome-rails'
gem 'seed_dumper', '~> 0.1.3'
gem 'gibbon', '~> 1.1.5'
gem 'daemons', '~> 1.2.2'
gem 'rollbar'
gem 'skylight'
gem 'reform', '~> 1.2.6'
gem 'daemon_controller', '~> 1.2.0'
gem 'react-rails'
gem "selectize-rails"
gem 'whenever', require: false
