source 'https://rubygems.org'

gem 'rails', '4.2.7.1'

group :assets do
  gem 'sass-rails'
  gem 'uglifier'
  gem 'coffee-script', '~> 2.4.1'
end

group :development do
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'quiet_assets', '~> 1.1.0'
  gem 'guard-rspec'
  gem 'spring'
  gem 'rubocop', require: false
  gem 'rack-mini-profiler'
  gem 'bullet'
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rbenv'
  gem 'capistrano-rails'
  gem 'capistrano-nc'
  gem 'capistrano3-delayed-job', '~> 1.0'
  gem 'capistrano-passenger', '= 0.0.1'
  gem "capistrano-scm-gitcopy"
  gem "rubycritic", :require => false
end

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'faker'
  gem 'shoulda-matchers'
  gem 'simplecov', :require => false
  gem 'database_cleaner'
end

group :development, :test do
  gem 'foreman', require: false
  gem 'rspec-rails', '~> 3.5'
  gem 'rspec-collection_matchers'
  gem 'spring-commands-rspec'
  gem 'factory_girl_rails'
end

# admin specific gems
gem 'tinymce-rails'
gem 'ransack'
gem 'aasm'
gem 'cancancan'
gem 'kaminari'

# other gems
gem 'exception_handler', '~> 0.3.45'
gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'momentjs-rails'
gem 'roadie-rails'
gem 'metamagic', '~> 3.1.7'
gem 'delayed_job_active_record'
gem 'zeroclipboard-rails'
gem 'roboto', '~> 0.2.0'
gem 'jquery-cookie-rails', '~> 1.3.1.1'
gem 'acts_as_list'

gem 'pg'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'devise', '~> 3.5.10'
gem 'carrierwave'
gem 'cloudinary'
gem 'wicked'
gem 'simple_form'
gem 'crummy', '~> 1.8.0'
gem 'friendly_id'
gem 'slim-rails'
gem 'newrelic_rpm'
gem 'braintree'
gem 'draper', '~> 2.1.0'
gem 'font-awesome-rails'
gem 'seed_dumper', '~> 0.1.3'
gem 'gibbon', '~> 1.1.5'
gem 'daemons'
gem 'rollbar'
gem 'skylight'
gem 'reform', '~> 1.2.6'
gem 'daemon_controller'
gem 'react-rails'
gem "selectize-rails"
gem 'whenever', require: false
