# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

if ENV['DOCKER_DEV'] == 'true'
  import './tasks.rake'
else
  require File.expand_path('../config/application', __FILE__)
  Forthepet::Application.load_tasks
end
