- name: setup users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
    shell: /bin/bash
    groups: sudo
  with_items: users
  tags: users

- name: setup user ssh keys
  authorized_key: user={{ item.name }} key="{{ item.key }}" state=present
  with_items: users
  tags: users

- name: setup users authorised keys for symlinking
  template: src=authorized_keys.j2 dest=/etc/authorized_keys
  tags: users
