# Dir[File.join(Rails.root, 'db', 'seeds', '*.rb')].sort.each { |seed| load seed }

# require_relative 'seeds/users'
# require_relative 'seeds/addresses'
# require_relative 'seeds/admins'
require_relative 'seeds/categories'
# require_relative 'seeds/products'
# require_relative 'seeds/deals'
# require_relative 'seeds/fine_prints'
# require_relative 'seeds/options'
# require_relative 'seeds/option_values'
# require_relative 'seeds/variants'
# require_relative 'seeds/orders'
# require_relative 'seeds/order_items'
# require_relative 'seeds/discounts'
